### PR TITLE
Fix require() call

### PR DESCRIPTION
**Pull request by Turbo87**
This should hopefully fix `Error: Cannot find module 'RSVP'` in https://travis-ci.org/emberjs/data/builds/119016376 (see https://github.com/emberjs/data/pull/4023)

### CODE REVIEW

**Comment by Turbo87** [comment]
looks like this broken in https://github.com/ember-cli/ember-cli-blueprint-test-helpers/pull/40

**Comment by rwjblue** [comment]
LGTM
